"use client";

import { useMemo, useState } from "react";
import { Building2, CheckCircle2, ChevronDown, ChevronUp, CreditCard, Plus, ReceiptText, Repeat2, RotateCcw, Trash2, Wifi, Zap } from "lucide-react";

type CustoEmpresa={id:number;descricao:string;categoria:string;valor:number;vencimento:string;observacao:string;recorrente?:boolean;frequencia?:"Mensal"|"Semanal"|"Anual";pago?:boolean;dataPagamento?:string};
const KEY="licitapro_custos_empresa";
const brl=(v:number)=>(Number(v)||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const mesKey=(data:string)=>data?data.slice(0,7):"sem-data";
const nomeMes=(key:string)=>{if(key==="sem-data")return"Sem vencimento";const [a,m]=key.split("-").map(Number);return new Date(a,m-1,1).toLocaleDateString("pt-BR",{month:"long",year:"numeric"})};

export default function CustosEmpresa(){
 const [custos,setCustos]=useState<CustoEmpresa[]>(()=>{if(typeof window==="undefined")return[];try{return JSON.parse(localStorage.getItem(KEY)||"[]")}catch{return[]}});
 const [descricao,setDescricao]=useState(""),[categoria,setCategoria]=useState("Aluguel"),[valor,setValor]=useState(""),[vencimento,setVencimento]=useState(""),[observacao,setObservacao]=useState(""),[recorrente,setRecorrente]=useState(false),[frequencia,setFrequencia]=useState<"Mensal"|"Semanal"|"Anual">("Mensal");
 const mesAtual=new Date().toISOString().slice(0,7);const [mesesAbertos,setMesesAbertos]=useState<Set<string>>(()=>new Set([mesAtual]));
 const salvar=(lista:CustoEmpresa[])=>{setCustos(lista);localStorage.setItem(KEY,JSON.stringify(lista));window.dispatchEvent(new Event("licitapro-custos-updated"))};
 const adicionar=()=>{if(!descricao.trim()){alert("Informe a descrição da conta.");return}if(!(Number(valor)>0)){alert("Informe o valor da conta.");return}salvar([{id:Date.now(),descricao:descricao.trim(),categoria,valor:Number(valor),vencimento,observacao:observacao.trim(),recorrente,frequencia:recorrente?frequencia:undefined,pago:false},...custos]);setDescricao("");setValor("");setVencimento("");setObservacao("");setRecorrente(false);setFrequencia("Mensal")};
 const excluir=(id:number)=>{if(confirm("Excluir este custo da empresa?"))salvar(custos.filter(c=>c.id!==id))};
 const marcarPago=(id:number,pago:boolean)=>salvar(custos.map(c=>c.id===id?{...c,pago,dataPagamento:pago?new Date().toISOString():undefined}:c));
 const alternarMes=(key:string)=>setMesesAbertos(prev=>{const next=new Set(prev);next.has(key)?next.delete(key):next.add(key);return next});
 const total=useMemo(()=>custos.reduce((s,c)=>s+(Number(c.valor)||0),0),[custos]);
 const totalPago=useMemo(()=>custos.filter(c=>c.pago).reduce((s,c)=>s+(Number(c.valor)||0),0),[custos]);
 const recorrentes=useMemo(()=>custos.filter(c=>c.recorrente),[custos]);
 const totalRecorrenteMensal=useMemo(()=>recorrentes.reduce((s,c)=>{const v=Number(c.valor)||0;if(c.frequencia==="Semanal")return s+v*4.345;if(c.frequencia==="Anual")return s+v/12;return s+v},0),[recorrentes]);
 const grupos=useMemo(()=>{const map:Record<string,CustoEmpresa[]>={};custos.forEach(c=>{const k=mesKey(c.vencimento);(map[k]??=[]).push(c)});return Object.entries(map).sort(([a],[b])=>b.localeCompare(a))},[custos]);
 const icone=(cat:string)=>cat==="Energia"?<Zap size={18}/>:cat==="Internet"?<Wifi size={18}/>:cat==="Cartão"?<CreditCard size={18}/>:cat==="Aluguel"?<Building2 size={18}/>:<ReceiptText size={18}/>;
 return <section className="companyCostsPage">
  <div className="licitacoesHeader"><div><h2>Custos da empresa</h2><p>Controle as contas por mês e marque o que já foi efetivamente pago.</p></div></div>
  <div className="companyCostsSummaryRow"><div className="companyCostsSummary"><span>Total cadastrado</span><strong>{brl(total)}</strong><small>{custos.length} {custos.length===1?"conta":"contas"}</small></div><div className="companyCostsSummary recurring"><span>Total já pago</span><strong>{brl(totalPago)}</strong><small>Somente contas pagas debitam o caixa</small></div><div className="companyCostsSummary recurring"><span>Custo recorrente mensal</span><strong>{brl(totalRecorrenteMensal)}</strong><small>{recorrentes.length} contas recorrentes</small></div></div>
  <div className="companyCostsForm recurringForm">
   <label><span>Descrição</span><input value={descricao} onChange={e=>setDescricao(e.target.value)} placeholder="Ex.: Aluguel do escritório"/></label><label><span>Categoria</span><select value={categoria} onChange={e=>setCategoria(e.target.value)}>{["Aluguel","Energia","Internet","Cartão","Telefone","Contabilidade","Impostos","Outros"].map(c=><option key={c}>{c}</option>)}</select></label><label><span>Valor</span><input type="number" min="0" step="0.01" value={valor} onChange={e=>setValor(e.target.value)} placeholder="0,00"/></label><label><span>Vencimento</span><input type="date" value={vencimento} onChange={e=>setVencimento(e.target.value)}/></label><label className="recurringCheck"><span>Recorrência</span><button className={recorrente?"recurringToggle active":"recurringToggle"} type="button" onClick={()=>setRecorrente(v=>!v)}><Repeat2 size={16}/>{recorrente?"Recorrente":"Conta única"}</button></label>{recorrente&&<label><span>Frequência</span><select value={frequencia} onChange={e=>setFrequencia(e.target.value as "Mensal"|"Semanal"|"Anual")}><option>Mensal</option><option>Semanal</option><option>Anual</option></select></label>}<label className="costObservation"><span>Observação</span><input value={observacao} onChange={e=>setObservacao(e.target.value)} placeholder="Opcional"/></label><button onClick={adicionar} type="button"><Plus size={17}/>Adicionar conta</button>
  </div>
  <div className="costMonths">{grupos.length===0?<div className="emptyState"><ReceiptText size={30}/><h3>Nenhum custo cadastrado</h3><p>Cadastre as contas da empresa para começar.</p></div>:grupos.map(([key,lista])=>{const aberto=mesesAbertos.has(key);const totalMes=lista.reduce((s,c)=>s+(Number(c.valor)||0),0);const pagoMes=lista.filter(c=>c.pago).reduce((s,c)=>s+(Number(c.valor)||0),0);return <div className="costMonthCard" key={key}><button className="costMonthHeader" type="button" onClick={()=>alternarMes(key)}><div><span>CALENDÁRIO DE CONTAS</span><strong>{nomeMes(key)}</strong><small>{lista.length} contas • {brl(totalMes)} • pago {brl(pagoMes)}</small></div>{aberto?<ChevronUp size={20}/>:<ChevronDown size={20}/>}</button>{aberto&&<div className="costMonthPopup"><div className="companyCostsList">{lista.sort((a,b)=>(a.vencimento||"").localeCompare(b.vencimento||"")).map(c=><div className={`companyCostRow ${c.pago?"paid":""}`} key={c.id}><div className="companyCostIcon">{icone(c.categoria)}</div><div className="companyCostInfo"><strong>{c.descricao}</strong><span>{c.categoria}{c.vencimento?` • Vence ${new Date(c.vencimento+"T00:00:00").toLocaleDateString("pt-BR")}`:""}</span>{c.recorrente&&<small className="recurringBadge"><Repeat2 size={11}/>Recorrente • {c.frequencia||"Mensal"}</small>}{c.observacao&&<small>{c.observacao}</small>}</div><strong className="companyCostValue">{brl(c.valor)}</strong><span className={c.pago?"costPaidBadge":"costPendingBadge"}>{c.pago?"Paga":"Pendente"}</span>{c.pago?<button className="costUndoBtn" onClick={()=>marcarPago(c.id,false)} type="button" title="Desfazer pagamento"><RotateCcw size={15}/>Desfazer</button>:<button className="costPayBtn" onClick={()=>marcarPago(c.id,true)} type="button"><CheckCircle2 size={15}/>Marcar paga</button>}<button onClick={()=>excluir(c.id)} type="button" title="Excluir"><Trash2 size={16}/></button></div>)}</div></div>}</div>})}</div>
 </section>
}
