"use client";

import { useMemo, useState } from "react";
import DetalhesLicitacao from "./DetalhesLicitacao";
import { Plus, Search, FileText, CalendarDays, Building2, ChevronRight, X, Save, Clock3, Globe2 } from "lucide-react";

type Licitacao = { id:number; orgao:string; edital:string; modalidade:string; data:string; horario?:string; portal?:string; status:string; observacoes:string; valorEstimado:number };
type Item = { quantidade:number; custo:number; frete:number; lanceAtual:number; resultado?:"em_disputa"|"ganhou"|"perdeu" };
type EstadoLicitacao={label:string;classe:string;concluida:boolean;comGanho:boolean};
const brl=(n:number)=>(Number(n)||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const STORAGE_KEY="licitapro_licitacoes";
const ITENS_PREFIX="licitapro_itens_";

export default function Licitacoes(){
 const [licitacoes,setLicitacoes]=useState<Licitacao[]>(()=>{if(typeof window==="undefined")return[];try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||"[]")}catch{return[]}});
 const [showForm,setShowForm]=useState(false),[search,setSearch]=useState("");
 const [licitacaoSelecionada,setLicitacaoSelecionada]=useState<Licitacao|null>(null);
 const [orgao,setOrgao]=useState(""),[edital,setEdital]=useState(""),[modalidade,setModalidade]=useState("Pregão Eletrônico"),[data,setData]=useState(""),[horario,setHorario]=useState(""),[portal,setPortal]=useState(""),[status,setStatus]=useState("Em andamento"),[observacoes,setObservacoes]=useState(""),[valorEstimado,setValorEstimado]=useState("");
 const salvarLicitacoes=(lista:Licitacao[])=>{setLicitacoes(lista);localStorage.setItem(STORAGE_KEY,JSON.stringify(lista))};
 const novaLicitacao=()=>{if(!orgao.trim()){alert("Informe o órgão.");return}if(!edital.trim()){alert("Informe o número do edital.");return}const nova:Licitacao={id:Date.now(),orgao:orgao.trim(),edital:edital.trim(),modalidade,data,horario,portal:portal.trim(),status,observacoes,valorEstimado:Number(valorEstimado)||0};salvarLicitacoes([nova,...licitacoes]);setOrgao("");setEdital("");setModalidade("Pregão Eletrônico");setData("");setHorario("");setPortal("");setStatus("Em andamento");setObservacoes("");setValorEstimado("");setShowForm(false)};
 const excluir=(id:number)=>{if(confirm("Tem certeza que deseja excluir esta licitação?"))salvarLicitacoes(licitacoes.filter(i=>i.id!==id))};
 const lerItens=(id:number):Item[]=>{try{const v=JSON.parse(localStorage.getItem(ITENS_PREFIX+id)||"[]");return Array.isArray(v)?v:[]}catch{return[]}};
 const estadoLicitacao=(l:Licitacao):EstadoLicitacao=>{const itens=lerItens(l.id);if(itens.length>0){const todosFinalizados=itens.every(i=>i.resultado==="ganhou"||i.resultado==="perdeu");if(todosFinalizados){const comGanho=itens.some(i=>i.resultado==="ganhou");return{label:"Concluída",classe:comGanho?"concluida-ganho":"concluida-perda",concluida:true,comGanho}}}return{label:l.status||"Em andamento",classe:(l.status||"Em andamento").toLowerCase().replaceAll(" ","-").replaceAll("ã","a"),concluida:false,comGanho:false}};
 const filtradas=useMemo(()=>{const t=search.toLowerCase().trim();const base=!t?licitacoes:licitacoes.filter(i=>{const e=estadoLicitacao(i);return i.orgao.toLowerCase().includes(t)||i.edital.toLowerCase().includes(t)||e.label.toLowerCase().includes(t)||(i.portal||"").toLowerCase().includes(t)});return [...base].sort((a,b)=>{const da=a.data?new Date(`${a.data}T${a.horario||"00:00"}:00`).getTime():Number.MAX_SAFE_INTEGER;const db=b.data?new Date(`${b.data}T${b.horario||"00:00"}:00`).getTime():Number.MAX_SAFE_INTEGER;return da-db||a.id-b.id})},[licitacoes,search,licitacaoSelecionada]);
 const financeiro=(id:number)=>{const itens=lerItens(id);let custo=0,ganho=0,possivelGanho=0;itens.forEach(i=>{const qtd=Number(i.quantidade)||0;const custoItem=qtd*(Number(i.custo)||0)+(Number(i.frete)||0);const valorLance=qtd*(Number(i.lanceAtual)||0);custo+=custoItem;if(i.resultado==="ganhou")ganho+=valorLance;if(i.resultado==="perdeu")possivelGanho+=Math.max(0,valorLance-custoItem)});return{custo,ganho,possivelGanho}};
 const emAndamento=licitacoes.filter(l=>!estadoLicitacao(l).concluida&&estadoLicitacao(l).label==="Em andamento").length;
 return <>{licitacaoSelecionada?<DetalhesLicitacao licitacao={licitacaoSelecionada} onVoltar={()=>setLicitacaoSelecionada(null)}/>:<section className="licitacoesPage">
  <div className="licitacoesHeader"><div><h2>Licitações</h2><p>Cadastre e acompanhe suas oportunidades.</p></div><button className="primaryBtn" onClick={()=>setShowForm(true)}><Plus size={18}/>Nova licitação</button></div>
  <div className="searchBar"><Search size={18}/><input placeholder="Pesquisar por órgão, edital, portal ou status..." value={search} onChange={e=>setSearch(e.target.value)}/></div>
  {showForm&&<div className="formPanel"><div className="formHeader"><div><h3>Nova licitação</h3><p>Cadastre os dados principais da licitação.</p></div><button className="iconBtn" onClick={()=>setShowForm(false)}><X size={20}/></button></div><div className="formGrid">
   <label className="formField"><span>Órgão *</span><div className="formInput"><Building2 size={16}/><input value={orgao} onChange={e=>setOrgao(e.target.value)} placeholder="Ex.: Prefeitura Municipal de Andrelândia"/></div></label>
   <label className="formField"><span>Número do edital *</span><div className="formInput"><FileText size={16}/><input value={edital} onChange={e=>setEdital(e.target.value)} placeholder="Ex.: PE 042/2026"/></div></label>
   <label className="formField"><span>Modalidade</span><select value={modalidade} onChange={e=>setModalidade(e.target.value)}>{["Pregão Eletrônico","Concorrência","Dispensa Eletrônica","Inexigibilidade","Tomada de Preços","Outra"].map(x=><option key={x}>{x}</option>)}</select></label>
   <label className="formField"><span>Data da disputa</span><div className="formInput"><CalendarDays size={16}/><input type="date" value={data} onChange={e=>setData(e.target.value)}/></div></label>
   <label className="formField"><span>Horário da licitação</span><div className="formInput"><Clock3 size={16}/><input type="time" value={horario} onChange={e=>setHorario(e.target.value)}/></div></label>
   <label className="formField"><span>Portal</span><div className="formInput"><Globe2 size={16}/><input value={portal} onChange={e=>setPortal(e.target.value)} placeholder="Ex.: Portal de Compras Públicas"/></div></label>
   <label className="formField"><span>Status</span><select value={status} onChange={e=>setStatus(e.target.value)}>{["Em andamento","Em análise","Vencida","Perdida","Cancelada"].map(x=><option key={x}>{x}</option>)}</select></label>
   <label className="formField"><span>Valor estimado</span><div className="formInput"><span className="currency">R$</span><input type="number" min="0" step="0.01" value={valorEstimado} onChange={e=>setValorEstimado(e.target.value)} placeholder="0,00"/></div></label>
   <label className="formField full"><span>Observações</span><textarea value={observacoes} onChange={e=>setObservacoes(e.target.value)} placeholder="Anotações importantes sobre esta licitação..." rows={4}/></label>
  </div><div className="formActions"><button className="cancelBtn" onClick={()=>setShowForm(false)}>Cancelar</button><button className="primaryBtn" onClick={novaLicitacao}><Save size={17}/>Salvar licitação</button></div></div>}
  <div className="summaryCards summaryCardsCompact"><div className="summaryCard"><span>Total de licitações</span><strong>{licitacoes.length}</strong></div><div className="summaryCard"><span>Em andamento</span><strong>{emAndamento}</strong></div></div>
  <div className="licitacoesList">{filtradas.length===0?<div className="emptyState"><div className="emptyIcon"><FileText size={30}/></div><h3>Nenhuma licitação cadastrada</h3><p>Comece cadastrando sua primeira licitação.</p><button className="primaryBtn" onClick={()=>setShowForm(true)}><Plus size={17}/>Nova licitação</button></div>:filtradas.map(item=>{const f=financeiro(item.id),estado=estadoLicitacao(item);return <div className="licitacaoCard" key={item.id}>
   <div className="licitacaoMain"><div className="licitacaoIcon"><FileText size={21}/></div><div className="licitacaoInfo"><h3>{item.orgao}</h3><div className="licitacaoMeta"><span>{item.edital}</span><span>{item.modalidade}</span>{item.data&&<span className="licitacaoDateHighlight"><CalendarDays size={13}/>{new Date(item.data+"T00:00:00").toLocaleDateString("pt-BR")}</span>}{item.horario&&<span className="licitacaoTimeHighlight"><Clock3 size={13}/>{item.horario}</span>}{item.portal&&<span>{item.portal}</span>}</div></div></div>
   <div className="licitacaoFinancials"><div className="licitacaoValue"><small>Valor estimado</small><strong>{brl(item.valorEstimado)}</strong></div><div className="licitacaoValue cost"><small>Custo</small><strong>{brl(f.custo)}</strong></div><div className="licitacaoValue won"><small>Valor ganho</small><strong>{brl(f.ganho)}</strong></div><div className="licitacaoValue possible"><small>Possível ganho total</small><strong>{brl(f.possivelGanho)}</strong></div></div>
   <span className={`statusPill ${estado.classe}`}>{estado.concluida&&!estado.comGanho?"Licitação perdida • Possível ganho":estado.label}</span><button className="openBtn" onClick={()=>setLicitacaoSelecionada(item)}>Abrir<ChevronRight size={16}/></button><button className="deleteBtn" onClick={()=>excluir(item.id)} title="Excluir"><X size={16}/></button>
  </div>})}</div>
 </section>}</>;
}